### ISSUE TITLE
sondes.yaml contains only HALO sondes

### ISSUE THREAD

**Issue by RobertPincus** [eurec4a/flight-phase-separation#1]
File `scripts/sondes.yaml` includes only the HALO sondes. I have a similar file from Geet - shall I add those, or keep a separate file and rename the existing one to `halo_sondes.yaml?`

**Comment by d70-t** [comment]
The other option would be to concat the files. The report.py should filter out the correct sondes afterwards. If you would opt to renaming it, I would also suggest to make an additional subfolder.

**Comment by d70-t** [comment]
:point_right: The current verification tool assumes that all sondes are in one file. If you decide to create multiple files, we would need to update the corresponding code as well.

**Comment by RobertPincus** [comment]
Fixed by fba5c46cadd2b9338445bd5251c350e2c877cbc4 using a file provided by @Geet-George
