### ISSUE TITLE
Sonde overlap among segments?

### ISSUE THREAD

**Issue by Geet-George** [eurec4a/flight-phase-separation#14]
For the HALO flight on 15th Feb, the last 2 circles were planned so that 1 sonde was an overlap between the two consecutively flown dropsonde-circles (i.e. no usual break of 15 minutes). 

Currently, the flight phase separation (FPS) files classify that single sonde in to one of the circles. However, to make the JOANNE circle products robust, we need this sonde to be present in both circles, i.e. Sonde `HALO-0215_s44` should be included in both `HALO-0215_c5` and `HALO-0215_c6`. 

For JOANNE, I am also making a sonde-2-circle reference list for Level-4, to identify the sondes present in the circles. Ideally, I'd like this to also take input straight from the FPS files. 

So, even if it is for just one sonde, it'll be nice to allow sondes to belong to multiple segments. Do we have any rules (or do we want any) stating that sondes should belong to only one segment?

**Comment by d70-t** [comment]
I am not aware of any rule which requires sondes to be only part of one circle. And I think exactly this instance was one of the reasons why we've included the list of sondes: such that it is possible to associate sondes not by time but by how they should be interpreted logically. So I am wondering why the sonde isn't associated with both circles already.

**Comment by Geet-George** [comment]
This was exactly what I was thinking. Thanks for the validation. I'll assign the sonde to both circles. How many of these irregularities that we have should be mentioned for Heike's HALO paper? Is it a good idea to give specific definitions in the paper, and all irregularities as an appendix or something?
