### ISSUE TITLE
SAM error 

### ISSUE THREAD

**Issue by Geet-George** [eurec4a/flight-phase-separation#18]
Dear Geet
I just spotted a mistake in the yaml file:
Sonde "HALO-0211_s60" shouldn't be part of circle 5 on the 11 Feb - it was dropped 2º east of circle east and 20min after the circle. Can you change that directly or should I ask Marc?
Cheers, raphaela

**Comment by d70-t** [comment]
The `sondes.yaml` [tells](https://github.com/eurec4a/flight-phase-separation/blob/master/scripts/sondes.yaml#L3046) that the sonde has been launched at `2020-02-11 18:51:58` which would be clearly inside of the circle (which is until `2020-02-11 18:55:35`). Is that launch time correct?
