### ISSUE TITLE
HALO flight phase file names don't mention version number

### ISSUE THREAD

**Issue by Geet-George** [eurec4a/flight-phase-separation#23]
To keep with EUREC4A's convention, we should add version numbers to the file names?

**Comment by d70-t** [comment]
We've had this discussion on mattermost. The conclusion has been that the only place where a version number is to be defined is in a tag of a specific git commit of this repository, but not in the files inside of this repository. The reason behind this is that we do not ever want to have two different files with the same version number.

We once had version numbers on files in this repository, but e.g. 5c3d0a92 changed the file while keeping the version number constant. What people should do if they want to refer to a "relased" version is to go to the [releases](https://github.com/eurec4a/flight-phase-separation/releases) and take the compiled release from there. We could argue that the compiled release file should have a more descriptive name an possibly also contain the version number etc.. in its file name. For that to work, we'll have to update the [release workflow](https://github.com/eurec4a/flight-phase-separation/blob/master/.github/workflows/compiled_release.yml#L27) and need to ensure that [`get_flight_segments`](https://github.com/eurec4a/pyeurec4a/blob/bdf67581190aee2aac1722ffbbaba836fca87124/eurec4a/__init__.py#L24) will be able to properly resolve that file name.

**Comment by Geet-George** [comment]
Agreed, sorry for restarting a resolved issue.
