### ISSUE TITLE
Better sorting for compiled yaml keys

### ISSUE THREAD

**Issue by d70-t** [eurec4a/flight-phase-separation#27]
Currently the keys in the compiled `all_flights.yaml` are sorted alphabetically. We might want to transition to a more human readable order.

**Comment by Geet-George** [comment]
Where is this `all_flights.yaml`? Heike also told me about it. I am a bit lost.

**Comment by d70-t** [comment]
It is autogenerated by [`compile.py`](https://github.com/eurec4a/flight-phase-separation/blob/master/scripts/compile.py) and is found as a [release asset](https://github.com/eurec4a/flight-phase-separation/releases/tag/v1.1). Users should preferably use this file, because that way, you only need to download one thing and it is possible to enumerate all flights without guessing the file names.

**Comment by Geet-George** [comment]
Okay, I should have known this. Feeling silly...
