### ISSUE TITLE
Create release to be published with HALO ESSD paper

### ISSUE THREAD

**Issue by d70-t** [eurec4a/flight-phase-separation#28]
We want to have a DOI which can be referenced in the HALO ESSD paper.
We probably need another Bird name (starting with letter b) for this. Suggestions welcome.

Candidates:

* [ ] [bee-eater](https://en.wikipedia.org/wiki/Bee-eater)
* [ ] [barn-owl](https://pbase.com/dlilly/image/142039705)
* [ ] [budgie](https://en.wikipedia.org/wiki/Budgerigar)

**Comment by RobertPincus** [comment]
There are many: https://pbase.com/dlilly/birds_starting_with_b

**Comment by RobertPincus** [comment]
I do love barn-owls.

**Comment by Geet-George** [comment]
Both good options! I just realised that surprisingly there are no original bird names starting with 'b', most have an adjective in the name which starts with 'b' (e.g. barn owl, bald eagle, black turnstone, etc.) or it comes from the name of another animal (e.g. bee eater). But no dedicated names like albatross, crow, duck, eagle, flamingo, goose, heron... Okay, as I write this list, I am even more bewildered that for some reason, `b` has been outcast in the **B**ird naming scheme.  Guess we should have had a bit more foresight before settling on the naming scheme.  😛

**Comment by d70-t** [comment]
Indeed, but as [it seems](https://en.wikipedia.org/wiki/List_of_birds_by_common_name) there are plenty of birds with spaces in their names for all the other letters as well 🤷‍♂️

**Comment by Geet-George** [comment]
Oooh... Found one! [Budgerigar](https://en.wikipedia.org/wiki/Budgerigar) or 'budgie'... I had heard of parakeets, which apparently is the American-English name for the bird.

**Comment by Geet-George** [comment]
> Indeed, but as [it seems](https://en.wikipedia.org/wiki/List_of_birds_by_common_name) there are plenty of birds with spaces in their names for all the other letters as well 🤷‍♂️

Yeah, I was just saying that there don't seem to be any dedicated bird names that don't come out of other word forms. All of this reminds me of a board game called [Wingspan](https://boardgamegeek.com/boardgame/266192/wingspan) which I played a lot when the lockdown first began last year. It is an awesome engine-building game, and the graphics and the paintings of birds are very beautiful. If you are into board games, I would definitely recommend this. Super fun!

**Comment by d70-t** [comment]
Oh, by the way, we'll also need an adjective 😬 😄 

* [ ] beautiful
* [ ] busy
* [ ] benefic

**Comment by d70-t** [comment]
> this reminds me of a board game called [Wingspan](https://boardgamegeek.com/boardgame/266192/wingspan)

I think I've seen the box before. But never played it. Must be the perfect preparation for our job :-)

**Comment by RobertPincus** [comment]
Wingspan was on my list of holiday gifts for my kids last year but didn't make the cut. Now I'm inspired. 

"beautiful-budgie?" 

I had software where the release names were apple varieties. Ashmead, Bramley, Cornish–Gilliflower, ...

**Comment by Geet-George** [comment]
> I had software where the release names were apple varieties. Ashmead, Bramley, Cornish–Gilliflower, ...

Haha... That must have been a lot of fun!

**Comment by Geet-George** [comment]
> "beautiful-budgie?"

I am fine with this, but I also know Tobi has had bee-eater in mind for a long time. I propose that we settle on 
`"beautiful bee-eater"`
 and not delay the release further? I think it is one of the final items hindering Heike's HALO-EUREC4A manuscript submission. 

The name is also a nice compromise because Robert gets the adjective, Tobi gets the bird name and I get the final word! 😁   Also, they do look [beautiful](https://www.google.com/search?q=bee+eater&tbm=isch&hl=en&sa=X&ved=2ahUKEwj82Z6y4_vwAhVE4bsIHf2oDMwQBXoECAEQVQ&biw=1920&bih=944&safe=images)...

**Comment by d70-t** [comment]
I'd be happy with beautiful budgie as well. And I think it sounds a little better. And the argument would still hold, it's only you and me changing roles :-)

For the release, we'll probably need proper names / ORCID / email / affiliations for @RobertPincus and @LSaffin as they've contributed since the last release and are not yet on zenodo's authors list. Could you two send me the details or tell if you don't want to be listed? Either here or via Mattermost / email?

**Comment by RobertPincus** [comment]
My ORCID is 0000-0002-0016-3470

**Comment by leosaffin** [comment]
Sorry I missed the bird conversation. I can confirm that wingspan is a great game for bird enthusiasts

Name: Leo Saffin
ORCID: 0000-0002-6744-7785
Email: l.saffin@leeds.ac.uk
Affiliations: University of Leeds
